# Generated by Django 3.1.2 on 2021-01-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_pelicula_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='foto',
        ),
    ]
