# Generated by Django 3.1.2 on 2021-01-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
