# Generated by Django 3.1.2 on 2021-01-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0004_auto_20210121_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='foto',
        ),
    ]
